for i = 10:-1:1
    iStr = int2str(i);
    projection(['imputedMarkers.chr' iStr '.merged'],['map.' iStr '.txt'], ...
    ['fastphase_chr' iStr '.txt.filtered'], ...
    'residuals_distancebased_for_asi.txt.filtered', 2 + i, ['projectedSNP.' iStr '.dat']);
end
